name: food101-sr
channels:
  - defaults
  - pytorch
dependencies:
  - blas=1.0=openblas
  - brotli-python=1.0.9=py38h313beb8_8
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2024.8.30=py38hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - filelock=3.13.1=py38hca03da5_0
  - freetype=2.13.3=h47d26ad_0
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.1.2=py38h8c48613_0
  - idna=3.7=py38hca03da5_0
  - jinja2=3.1.4=py38hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.30=hf2bb037_2
  - libpng=1.6.50=h5c318fc_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py38h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py38hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.1=py38hca03da5_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.0.18=h9b4081a_0
  - pillow=10.4.0=py38h80987f9_0
  - pip=24.2=py38hca03da5_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.20=hb885b13_0
  - pytorch=2.4.1=py3.8_0
  - pyyaml=6.0.2=py38h80987f9_0
  - readline=8.3=h0b18652_0
  - requests=2.32.3=py38hca03da5_0
  - setuptools=75.1.0=py38hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - sympy=1.13.3=py38hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.4.1=py38_cpu
  - torchvision=0.20.0=py38_cpu
  - urllib3=2.2.3=py38hca03da5_0
  - wheel=0.44.0=py38hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - eval-type-backport==0.3.1
      - fonttools==4.57.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - matplotlib==3.7.5
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - platformdirs==4.3.6
      - protobuf==5.29.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - scipy==1.10.1
      - sentry-sdk==2.49.0
      - six==1.17.0
      - smmap==5.0.2
      - tifffile==2023.7.10
      - tqdm==4.67.1
      - types-requests==2.32.0.20241016
      - types-tqdm==4.67.0.20241221
      - typing-extensions==4.13.2
      - wandb==0.24.0
      - zipp==3.20.2
prefix: /Users/jedrek/miniconda3/envs/food101-sr
