program: train.py
method: bayes
metric:
  name: val_psnr
  goal: maximize
parameters:
  architecture:
    # Test which structure handles your food data best
    values: ["SRCNN", "RESNET", "AttentionSR"] 
  loss_function:
    # STRICTLY pixel-based losses for stability
    values: ["mae", "nlpd","mse"] 
  lr:
    min: 0.0001
    max: 0.001
  batch_size:
    values: [8,16, 32] 
  epochs:
    value: 10
  subset:
    value: 0.1