program: train.py
method: bayes
metric:
  name: val_psnr
  goal: maximize
parameters:
  architecture:
    value: "SRCNN"  
  loss_function:
    values: ["mae", "mse","nlpd"] 
  lr:
    min: 0.0001
    max: 0.001     
  batch_size:
    values: [16, 32, 64]
  subset:
    value: 0.025      
  epochs:
    value: 10